version: '3.3'
services:
  client:
    build:
      context:  ./client
      dockerfile: Dockerfile
    expose:
      - "80"
    ports:
      - "80:80"
  server:
    build:
      context:  ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
