apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-simple-chat
spec:
  environments:
    - name: dev
      authorization:
      - role: RadixAppAdmin
        groups:
        - "g_radix_platform_user"
    - name: prod
      authorization:
      - role: RadixAppAdmin
        groups:
        - "g_radix_platform_user"
  components:
    - name: client
      src: ./client/
      ports:
       - 80
      public: true
    - name: socket-server
      src: ./server/
      ports:
       - 8000
      public: false
